version: '3.8'

services:
  # 1. PHP Service (ทำงานบน Apache)
  php-app:
    # build: . บอกให้สร้าง Image จาก Dockerfile ในโฟลเดอร์นี้
    build: .
    container_name: my-php-app
    restart: unless-stopped
    # --- ลบบรรทัด volumes ตรงนี้ออกไป ---
    # volumes:
    #   - ./src:/var/www/html/
    ports:
      - "8080:80"
    environment:
      - MYSQL_HOST=mysql-db
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    depends_on:
      - mysql-db

  # 2. MySQL Database Service
  mysql-db:
    image: mysql:8.0
    container_name: my-mysql-db
    restart: unless-stopped
    command: --default-authentication-plugin=mysql_native_password
    environment:
      # กำหนดรหัสผ่าน root และสร้างฐานข้อมูล/ผู้ใช้เริ่มต้น
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    volumes:
      - mysql-data:/var/lib/mysql # เก็บข้อมูลฐานข้อมูลไว้บน Volume เพื่อไม่ให้ข้อมูลหาย

  # 3. phpMyAdmin Service
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: my-phpmyadmin
    restart: unless-stopped
    ports:
      - "8081:80" # แมพพอร์ต 8081 สำหรับเข้าหน้า phpMyAdmin
    environment:
      - PMA_HOST=mysql-db # ระบุเซิร์ฟเวอร์ฐานข้อมูลที่จะเชื่อมต่อ
      - PMA_PORT=3306
      - UPLOAD_LIMIT=300M # เพิ่มขนาดไฟล์อัปโหลด (ถ้าต้องการ)
    depends_on:
      - mysql-db

# กำหนด Volumes สำหรับเก็บข้อมูลถาวร
volumes:
  mysql-data: