version: "3.9"

services:
  app:
    build:
      context: ./php
      dockerfile: Dockerfile
    container_name: php-app
    environment:
      APACHE_DOCUMENT_ROOT: /var/www/html/public
      MYSQL_HOST: db
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - ./src:/var/www/html
    ports:
      - "${APP_PORT:-8080}:80"
    depends_on:
      - db
    networks:
      - appnet
    restart: unless-stopped

  db:
    image: mysql:8.0
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - db_data:/var/lib/mysql
      - ./mysql/init:/docker-entrypoint-initdb.d
    ports:
      - "${DB_PORT:-3306}:3306"
    networks:
      - appnet
    restart: unless-stopped

  phpmyadmin:
    image: phpmyadmin:5.2
    container_name: phpmyadmin
    environment:
      PMA_HOST: db
      PMA_USER: ${MYSQL_USER}
      PMA_PASSWORD: ${MYSQL_PASSWORD}
      UPLOAD_LIMIT: 128M
    ports:
      - "${PMA_PORT:-8081}:80"
    depends_on:
      - db
    networks:
      - appnet
    restart: unless-stopped

networks:
  appnet:

volumes:
  db_data:
