# docker-compose.yml

version: '3.8'

services:
  # Service สำหรับ PHP และ Apache Web Server
  php-app:
    build: .
    container_name: my-php-app
    ports:
      - "8887:80" # เข้าถึงเว็บผ่าน http://localhost:8887
    volumes:
      - ./src:/var/www/html/ # Map โฟลเดอร์ src เข้าไปใน container
    depends_on:
      - db
    networks:
      - my-app-network

  # Service สำหรับ MySQL Database
  db:
    image: mysql:8.0
    container_name: my-mysql-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: your_strong_password # <--- เปลี่ยนเป็นรหัสผ่านของคุณ
      MYSQL_DATABASE: my_php_app_db
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    volumes:
      - db-data:/var/lib/mysql # เก็บข้อมูล database แม้จะปิด container ไปแล้ว
    networks:
      - my-app-network

  # Service สำหรับ phpMyAdmin
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: my-phpmyadmin
    ports:
      - "8083:80" # เข้าถึง phpMyAdmin ผ่าน http://localhost:8083
    environment:
      PMA_HOST: db # ชื่อ service ของ MySQL
      MYSQL_ROOT_PASSWORD: root1234 # <--- ต้องตรงกับ MYSQL_ROOT_PASSWORD ของ db
    depends_on:
      - db
    networks:
      - my-app-network

# กำหนด Network ให้ services คุยกันได้
networks:
  my-app-network:
    driver: bridge

# กำหนด Volume สำหรับเก็บข้อมูล Database
volumes:
  db-data: